//! # gnucash-sys
//!
//! FFI bindings and safe Rust wrappers for the GnuCash engine library.
//!
//! This crate provides low-level bindings to libgnucash, allowing Rust programs
//! to interact with GnuCash's accounting engine.
//!
//! ## Core Types
//!
//! The library provides safe wrappers around GnuCash's core entity types:
//!
//! - [`Book`] - Top-level container for all financial data
//! - [`Account`] - Hierarchical ledger for tracking splits
//! - [`Transaction`] - Double-entry accounting record
//! - [`Split`] - Single entry in a transaction
//! - [`Guid`] - 128-bit unique identifier
//! - [`Numeric`] - Rational number (numerator/denominator)
//!
//! ## Example
//!
//! ```ignore
//! use gnucash_sys::{Book, Account, Transaction, Split, Numeric, GNCAccountType};
//!
//! // Create a new book
//! let book = Book::new();
//!
//! // Create accounts
//! let root = Account::new(&book);
//! root.begin_edit();
//! root.set_name("Root");
//! root.set_type(GNCAccountType::ACCT_TYPE_ROOT);
//! root.commit_edit();
//!
//! let checking = Account::new(&book);
//! checking.begin_edit();
//! checking.set_name("Checking");
//! checking.set_type(GNCAccountType::ACCT_TYPE_BANK);
//! checking.commit_edit();
//! root.append_child(&checking);
//!
//! // Create a transaction with splits
//! let txn = Transaction::new(&book);
//! txn.begin_edit();
//! txn.set_description("Opening balance");
//! txn.set_date(1, 1, 2024);
//!
//! let split = Split::new(&book);
//! split.set_account(&checking);
//! split.set_transaction(&txn);
//! split.set_amount(Numeric::new(10000, 100)); // $100.00
//! split.set_value(Numeric::new(10000, 100));
//!
//! txn.commit_edit();
//!
//! // Iterate over account children
//! for child in root.children() {
//!     println!("Child account: {:?}", child.name());
//! }
//!
//! // Iterate over transaction splits
//! for split in txn.splits() {
//!     println!("Split amount: {:?}", split.amount());
//! }
//! ```
//!
//! ## Building
//!
//! This crate requires:
//! - GnuCash source code (set `GNUCASH_SRC` env var, default: `../gnucash`)
//! - GnuCash built (set `GNUCASH_BUILD` env var, default: `../gnucash/build`)
//! - glib-2.0 development libraries
//!
//! ## Safety
//!
//! The safe wrappers handle memory management via RAII (Drop trait), but the
//! underlying GnuCash library is not thread-safe. While the wrapper types
//! implement `Send`, concurrent access requires external synchronization.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

/// Raw FFI bindings generated by bindgen.
///
/// These bindings are automatically generated from the GnuCash C headers.
/// Most users should prefer the safe wrapper types instead.
#[allow(
    clippy::all,
    unpredictable_function_pointer_comparisons,
    unnecessary_transmutes,
    rustdoc::broken_intra_doc_links,
    rustdoc::invalid_html_tags,
    rustdoc::bare_urls
)]
pub mod ffi {
    #[cfg(docsrs)]
    include!("bindings_generated.rs");
    #[cfg(not(docsrs))]
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

/// Error types for gnucash-sys operations.
pub mod error;

/// Iterators for GnuCash collections.
pub mod iter;

/// Safe Rust wrappers for core types (Guid, Numeric).
pub mod types;

/// Safe wrapper for QofBook.
pub mod book;

/// Safe wrapper for Account.
pub mod account;

/// Safe wrapper for Transaction.
pub mod transaction;

/// Safe wrapper for Split.
pub mod split;

/// Safe wrapper for QofSession.
pub mod session;

/// Safe wrappers for Price and PriceDB.
pub mod price;

// Re-export main types at crate root
pub use account::{Account, GNCAccountType};
pub use book::Book;
pub use error::{Error, Result};
pub use iter::{AccountChildren, AccountDescendants, AccountSplits, TransactionSplits};
pub use split::Split;
pub use transaction::Transaction;
pub use types::{Guid, Numeric, GUID_ENCODING_LENGTH};

// Re-export session types
pub use session::{init_engine, is_engine_initialized, QofBackendError, Session, SessionOpenMode};

// Re-export reconcile and txn_type constants
pub use split::reconcile;
pub use transaction::txn_type;

// Re-export price types
pub use price::{Price, PriceDB, PriceSource};
